config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :articles do
    collection do
      get :send_last, to: 'articles#send_last_articles', as: :send_last
      get :send_last_users, to: 'articles#send_last_users_articles', as: :send_last_users
    end
  resources :comments
  end

  root 'welcome#index'

end

app/models/admin_user.rb
# Admin user, used by ActiveAdmin
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
# Clase articulo. Tiene muchos comentarios.
# dependent: :destroy significa que los elimina si eliminamos articulos
# validar que exista el titulo y que sea de 5 char minimo
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: { minimum: 5 }

  def self.last_created(total_articles)
    Article.order(created_at: :desc).limit(total_articles)
  end
end

app/models/comment.rb
# Clase comment. Pertenece a un articulo
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
# Clase User, generada por Devise para poder loguearse en la aplicacion
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

  def self.last_created(total_users)
    User.order(created_at: :desc).limit(total_users)
  end

  def last_created_articles(total_articles)
    articles.order(created_at: :desc).limit(total_articles)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0, 20])
    end
    user
  end
end

app/controllers/application_controller.rb
# Clase Application controller
# Se define set_locale para la internacionalizacion
# Default URL options para setear los parametros desde url localhost:3000/es
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :set_locale
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/articles_controller.rb
# clase ArticlesController
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def article
    @article ||= Article.find(params[:id])
  end

  def show
    article
  end

  def edit
    article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    article
    authorize @article
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    article
    @article.destroy
    redirect_to articles_path
  end

  def send_last_articles
    @articles = Article.last_created(10)
    ArticleMailer.email_last_art(current_user.email, @articles).deliver!
    flash[:notice] = 'Articles have been sent.'
    redirect_to root_path
  end

  def send_last_users_articles
    HardWorker.perform_async(current_user.email, 5, 10)
    render nothing: true
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
# Clase comments controller
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @comment = article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  def article
    @article = Article.find(params[:article_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# Callbacks class used by google and facebook omniauth
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
# Clase welcomeController
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2
        = pluralize(@article.errors.count, "error ")
        | prohibited 
        | this article from being saved:
      ul
        - @article.errors.full_messages.each do |msg|
          li= msg
  p
    = f.label :title
    br/
    = f.text_field :title
  p
    = f.label :text
    br/
    = f.text_area :text
  p
    = f.submit

app/views/articles/_processing.html.slim
p ="We are processing your request"

app/views/articles/edit.html.slim
h1 =t(:editing_art)
= render 'form'
= link_to t(:back), articles_path

app/views/articles/index.html.slim
h1 =t(:listing_art)

= link_to t(:new_art), new_article_path
table
  tr
    th =t(:title)
    th =t(:text)
    th ="Author"
    th colspan="3"
  - @articles.each do |article|
    tr
      td= article.title
      td= article.text
      td= article.user.email
      td= link_to t(:show), article_path(article)
      -if policy(article).update?
        td= link_to t(:edit), edit_article_path(article)
      -if policy(article).update?
        td= link_to t(:destroy), article_path(article), :method => :delete, :data => {:confirm => t(:u_sure)}

= link_to "Enviar Mail", send_last_articles_path
p
= button_tag "Enviar 10 de ultimos 5", :id => 'send_last_users', remote: true
p
div id="processing-message"
p

app/views/articles/new.html.slim
h1 =t(:new_art)
= render 'form'
= link_to t(:back), articles_path

app/views/articles/send_last_users_articles.js.erb
$('#task-form').html("<%= j (render 'processing') %>");
$('#task-form').slideDown(100);

app/views/articles/show.html.slim
p
  strong =t(:title)
  |:
  = @article.title
p
  strong =t(:text)
  |:
  = @article.text
p
  strong ="Author"
  |:
  = @article.user.email
h2 =t(:comments)
= render @article.comments
h2 =t(:add_comment)
= render 'comments/form'
-if policy(@article).update?
  = link_to t(:edit), edit_article_path(@article)
  | \
= link_to t(:back), articles_path

app/views/comments/_comment.html.slim
p
  strong =t(:commenter)
  |:
  = comment.commenter
p
  strong =t(:comment)
  |:
  = comment.body


-if policy(comment).destroy?
  p= link_to t(:destroy), [comment.article, comment], :method => :delete, :data => {:confirm => t(:u_sure)}

app/views/comments/_form.html.slim
= form_for([@article, @article.comments.build]) do |f|
  p
    = f.label :commenter
    br/
    = f.text_field :commenter
  p
    = f.label :body
    br/
    = f.text_area :body
  p
    = f.submit

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : "Blog"
    = csrf_meta_tags
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /![if lt IE 9]
      | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script
    = stylesheet_link_tag "application", :media => "all"
    /! For third-generation iPad with high-resolution Retina display:
    /! Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    /! For iPhone with high-resolution Retina display:
    /! Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    /! For first- and second-generation iPad:
    /! Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /! Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /! For all other devices
    /! Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  body
    .navbar.navbar-default.navbar-static-top
      .container

        button.navbar-toggle data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#"  Blog
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3

        /! /span
      /! /row
      footer



        p © Wolox 2015


        - if user_signed_in?
          =link_to t(:logout), destroy_user_session_path, :method => :delete
        - else
          =link_to t(:login),new_user_session_path
          | \
          =link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2)
          | \
          = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
    /! /container

app/views/welcome/index.html.slim
h1 =t(:hello_rails)
= link_to t(:my_blog), controller: 'articles'